---
- name: Copy certs
  copy:
    src: ./keys
    dest: /etc/asterisk

- name: remove compressed file
  file:
    path: /etc/asterisk/sip.conf
    state: absent

- name: Applies http configuration
  template:
    src: http.conf.j2
    dest: /etc/asterisk/http.conf
    owner: root
    group: root
    mode: 644
  notify: update_asterisk

- name: Applies extensions configuration
  template:
    src: extensions.conf.j2
    dest: /etc/asterisk/extensions.conf
    owner: root
    group: root
    mode: 644
  notify: update_asterisk

- name: Applies pjsip configuration
  template:
    src: pjsip.conf.j2
    dest: /etc/asterisk/pjsip.conf
    owner: root
    group: root
    mode: 644
  notify: update_asterisk

- name: Applies rtp configuration
  template:
    src: rtp.conf.j2
    dest: /etc/asterisk/rtp.conf
    owner: root
    group: root
    mode: 644
  notify: update_asterisk